name: Coupon
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.0=py37_0
  - asn1crypto=1.2.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2019.10.16=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2019.9.11=py37_0
  - cffi=1.13.2=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.8=py37ha12b0ac_0
  - cssselect=1.1.0=py_0
  - decorator=4.4.1=py_0
  - easydict=1.9=py_0
  - ffmpeg=4.0=h01ea3c9_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.63.1=hd977a24_0
  - graphite2=1.3.13=h2098e52_0
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hfa1e0ec_1
  - icu=58.2=h4b95b61_1
  - idna=2.8=py37_0
  - intel-openmp=2019.4=233
  - ipython=7.9.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jasper=2.0.14=h636a363_1
  - jedi=0.15.1=py37_0
  - jpeg=9b=he5867d9_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_0
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.9=hf6e021a_1
  - libxslt=1.1.33=h33a18ac_0
  - lxml=4.4.1=py37hef8c89e_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.17.2=py37h99e6662_0
  - numpy-base=1.17.2=py37h6575580_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1d=h1de35cc_3
  - parso=0.5.1=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h1de35cc_0
  - prettytable=0.7.2=py_3
  - prompt_toolkit=2.0.10=py_0
  - ptyprocess=0.6.0=py37_0
  - py-opencv=3.4.2=py37h7c891bd_1
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.1.0=py37_0
  - pyquery=1.4.0=py37_0
  - pysocks=1.7.1=py37_0
  - python=3.7.5=h359304d_0
  - python.app=2=py37_9
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py37_0
  - selenium=3.141.0=py37h1de35cc_0
  - setuptools=41.6.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.24.2=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
